version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hisaabkhata-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hisaabkhata
      POSTGRES_USER: hk_user
      POSTGRES_PASSWORD: hk_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
