spring.application.name=hisaab-khata

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/hisaabkhata?stringtype=unspecified
spring.datasource.username=hk_user
spring.datasource.password=hk_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate - schema managed by Flyway
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.secret="YOUR256BIT_SECRET_KEY_32_CHARACTERS_MINIMUM_XXXXXXXX"
security.jwt.expiry=86400000
